Var char x;
Const E2 = 'a';
Const E = 1;Const E3 = 34;
Const E1 = 'b';
Var integer x1;


Var integer eita, n1[100], n = 50, n7 = 10, teste[45], beicola[24];
integer MAXITER = 0, n2;
integer nome[100];
Char n4 = 'x',a;
char mm,nn,ab = '3';
char mm2,nn2 = 'n',ab2;
integer mm3 = 23,nn3,ab3 = 3;
integer mm4,nn4 = 55,ab4;
char vet[256];
integer vet2[33];
integer veeet;
char slaus;
var char nome2[2047], nome31[110], nomezin = 'J';
integer nome433[2047], integer32[20];
char nome24[2047], nome3[20];
integer fed = 31333;
Const n5= 'c';
Const n8 = 0x0A;
Const oi = 'f';
var integer n9 = 10;
const p = 3;
;  
